author: Scriblon
database: false
description: Adds Chances on Crafting.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.scriblon.plugins.chancecraft.Chancecraft
name: ChanceCraft
startup: postworld
version: '0.1'
softdepend: [Permissions, iConomy, BOSEconomy, Stats, Jobs, BukkitContrib]
